### ISSUE TITLE
selecting cell doesn't always update the lighting chart properly

### ISSUE THREAD

**Issue by thuytle** [civic-data-design-lab/atlas-lighting#101]
for example, this should say "high" but say "medium"

<img width="1435" alt="screen shot 2017-02-27 at 12 22 31 pm" src="https://cloud.githubusercontent.com/assets/1759051/23371884/9147f5e6-fce7-11e6-8fd2-82ad34bd00b3.png">

also not sure if we care right now but the address tag still stays on if mouse hover outside of map

**Comment by egeozin** [comment]
Yes, that's because currently, when a cell is selected we are only updating the average and we are not calculating the median, that's an easy fix, but first we have to make sure whether we want to update right panel or show the info in a pop-up.

**Comment by cosmicespresso** [comment]
Will be solved by the new "Selected cell report card" approach. Closing.
