### ISSUE TITLE
I'm changing the all_charts css back to previous

### ISSUE THREAD

**Issue by egeozin** [civic-data-design-lab/atlas-lighting#102]
Thuy, why do you change it? 

Now all the datasets on the right panel have more limited space.

<img width="365" alt="why" src="https://cloud.githubusercontent.com/assets/14356218/23375526/ae445c8e-fcf6-11e6-8a73-1412a45f794e.png">

Tell me what do you want to do, I will change it accordingly.

**Comment by thuytle** [comment]
hi Ege, I changed it because in the case study there are back and next buttons in front so if we don't reduce it the charts will hide behind the buttons but it's not that big of a deal
