### ISSUE TITLE
Users need to know that the selected datasets on the right are collapsible.

### ISSUE THREAD

**Issue by egeozin** [civic-data-design-lab/atlas-lighting#104]
Except streetview.

A UI cue is necessary.

**Comment by egeozin** [comment]
@Kallirroi , can you make a suggestion? I can then implement it.

**Comment by cosmicespresso** [comment]
I added this `.chart-title-collapsible:hover` to the CSS and the graphs in `grid.html` except the Light Average, for now its a simple `font-size` change but we can customize it a bit better.

**Comment by egeozin** [comment]
Thanks @Kallirroi

**Comment by egeozin** [comment]
Do you think it's better to  put " + " near the title(when collapsed) and " - " (when open)?

Or up and down arrows ?

**Comment by cosmicespresso** [comment]
Yeah I think arrows are better! We can use the same icon and then rotate it via CSS.
