### ISSUE TITLE
When filtering income data, cells with 0 values should be treated as no value

### ISSUE THREAD

**Issue by egeozin** [civic-data-design-lab/atlas-lighting#106]

**Comment by cosmicespresso** [comment]
Not sure I see something wrong with Income Chart? 
I added this line: `var iGroup = incomeDimension.group().reduceSum(function(d){return d.income>0;});` but it didn't change the graph.

**Comment by egeozin** [comment]
Yeah, I think what Dennis meant is instead of showing 0 on the left we have to replace it with a text saying "no value" or "no data".

**Comment by cosmicespresso** [comment]
thats not possible and also not correct I think...

**Comment by egeozin** [comment]
Let me ask him again!

**Comment by egeozin** [comment]
From Dennis' email: "So lets say someone selects a range of income values from the histogram. If the range is from an income of $0 - $50,000, all of the cells that have the value 0 should not be included. This is because the cells with 0 value don't have anyone living in them so there is no actual income associated with them." 

This is simple, I will implemrnt this.

**Comment by egeozin** [comment]
Fixed: a7b03c2
