### ISSUE TITLE
CASE STUDIES update: Turn into independent page with static images

### ISSUE THREAD

**Issue by cosmicespresso** [civic-data-design-lab/atlas-lighting#108]
Similar to the "About" page. There will be no interactivity, just static images embedded in a slideshow.

Hayro will assist with the text and details.

**Comment by thuytle** [comment]
Why are we making this change? Also I have a review tomorrow so will be a bit tight on time here

**Comment by hgunc** [comment]
@egeozin 

Here is the code that Thuy sent:
https://www.dropbox.com/sh/dskapnmq0h3haqd/AABX1nBjY9-FAQMBPQxyv2W-a?dl=0

We want to add a simple "Case Studies" dropdown next to about tab on the top. Let's add this as "Light Use in Different Income Groups"

We also need to add ATLAS tab that should take us to Chicago MSA


<img width="377" alt="screen shot 2017-03-04 at 8 26 52 pm" src="https://cloud.githubusercontent.com/assets/24460295/23583657/f90ea708-0118-11e7-9e00-53e5a4842ac4.png">

**Comment by cosmicespresso** [comment]
Who is taking care of implementing this? @thuytle @hgunc @egeozin

**Comment by egeozin** [comment]
@Kallirroi  If you have time, can you look into this ?

**Comment by egeozin** [comment]
Thuy sent me the html and css files.

**Comment by cosmicespresso** [comment]
@hgunc @egeozin I will take care of this but the OBI chart needs some feedback from you and Sarah (see my post in the other thread).
@egeozin where are the files?

**Comment by egeozin** [comment]
I will send them in 5.

**Comment by egeozin** [comment]
Sent.

**Comment by cosmicespresso** [comment]
Todos:

- [x] add a simple "Case Studies" dropdown next to about tab on the top. Let's add this as "Light Use in Different Income Groups"

- [x] integrate Thuy's work

- [x] add ATLAS tab that should take us to Chicago MSA

**Comment by cosmicespresso** [comment]
@hgunc @egeozin can you test drive this? I just pushed it.

**Comment by egeozin** [comment]
"Cannot GET /case.html" error on blank page when the case study is clicked  (route is : **http://localhost:8080/case.html**)

[UPDATE] After rebuilding, I get the same error

[UPDATE] Now updated Dockerfile, trying again...

**Comment by egeozin** [comment]
It worked after updating Dockerfile. Now rebuilding in google compute...

(Fixed in 6c4469c)

Apart from navbar fonts(Different from the one we use), everything looks cool.

**Comment by egeozin** [comment]
@Kallirroi  How did you manage to see it without updating Dockerfile?

@hgunc  You can check the website.

**Comment by cosmicespresso** [comment]
Good catch, 	069d1bc takes care of the typeface change.

Not sure I like the fact that the image is taller than the viewport (and that you have to scroll to see the slideshow buttons, at least for my screen). 

Hayro?

**Comment by cosmicespresso** [comment]
UPDATE: Thuy was not sourcing Bootstrap.css, fixed it and now it looks better but maybe too small:
![image](https://cloud.githubusercontent.com/assets/10440556/23595645/9e593de4-01f1-11e7-8ab8-84c4b8fbb9b7.png)

**Comment by hgunc** [comment]
@egeozin 
Can you replace 3 images with the corresponding images?
7_2.png
9_2.png
10_2.png
https://www.dropbox.com/sh/yrl1tr48spjs8qz/AACAFthI6PLRrG3Kg9tH7GZda?dl=0

**Comment by egeozin** [comment]
Updated
