### ISSUE TITLE
OBI updates

### ISSUE THREAD

**Issue by cosmicespresso** [civic-data-design-lab/atlas-lighting#109]
- [x] Make sure the weird behavior is not there (flashing)

- [x] The MEDIUM/LOW etc indicator should also change when the value changes

- [x] Add AM and PM near the hours (or some indication of day/night)

**Comment by cosmicespresso** [comment]
![image](https://cloud.githubusercontent.com/assets/10440556/23477259/697b4efa-fe8b-11e6-8f01-7f8457385399.png)

@egeozin IT FINALLY WORKS 💯  
(or at least we don't have the flashing thing!)

**Comment by egeozin** [comment]
SO HAPPY!

**Comment by Kallirroi** [comment]
Almost done.
Last bug:

- [ ] When OBI shows, the light average chart indicated value lags one update.

**Comment by cosmicespresso** [comment]
Unfortunately, its impossible to have everything interact with everything at the same time. We need to lock either the brush on the ligAve when the OBI is ON, or vice versa. I can explain more later. Also tried to implement a dc.js time filter, but that too fails because the data is formatted in an unfriendly way (its a question of the data matrix and the `ndx` object).

**Comment by egeozin** [comment]
You know what, I think we can prevent brushes on other charts when OBI is selected as you suggested. Also, we could write an instruction that when OBI is present the other charts will not be filterable.

**Comment by hgunc** [comment]
<img width="308" alt="screen shot 2017-03-03 at 11 33 25 am" src="https://cloud.githubusercontent.com/assets/24460295/23559586/7adbdd92-0005-11e7-8272-3d7074474416.png">

**Comment by hgunc** [comment]
am pm looks little weird on my screen
also  if we want to use am pm we need to convert 14 pm to 2pm.

if this is hard lets just go ahead and put ":00" to all
9 am - 10 am should then read  9:00 - 10:00

**Comment by cosmicespresso** [comment]
Updated list of tasks

- [ ] disable the value on the light intensity when OBI is showing

- [x] put ":00" to hour indication

- [x] shorten the title so that the 'x' can fit

**Comment by cosmicespresso** [comment]
@hgunc I need some input regarding the OBI chart - if we take out the digits and just keep the word (HIGH/MEDIUM etc) then it is always HIGH when we are using the time filter (see below). 

![image](https://cloud.githubusercontent.com/assets/10440556/23589828/c477e394-01a2-11e7-84c9-73bf0f80306d.png)


I think that the quickest fix is to not show the light average chart at all when OBI is on.

**Comment by hgunc** [comment]
@Kallirroi I will look into this first thing tomorrow. Don't think that we forgot about it! this is a very important piece of the tool
