### ISSUE TITLE
[Unreliable] Google Street View black screen

### ISSUE THREAD

**Issue by egeozin** [civic-data-design-lab/atlas-lighting#122]
Personally, I saw them worked %30 of the time. 

I think it's related to API call, but I'm not sure whether our script is problem.

**Comment by egeozin** [comment]
@Kallirroi, could you also try this: if the street view is not showing, can you open the inspector and select a cell, and if you still do not see it, can you close the inspector and select a cell again to check if you can then see the panorama?

**Comment by cosmicespresso** [comment]
Sometimes this has worked, but not consistently. Nothing has worked consistently! :p

**Comment by egeozin** [comment]
Oh dear! The only adverb we can associate with street view is sometimes.

**Comment by egeozin** [comment]
Also, have you been able to see any street view on LA?

**Comment by cosmicespresso** [comment]
Nope. I also checked Safari. Same situation.

UPDATE: Actually I do see some street view in LA:
![image](https://cloud.githubusercontent.com/assets/10440556/23520388/d3429254-ff48-11e6-9c79-2e3a231a7a19.png)

The console seems to do the trick.

**Comment by egeozin** [comment]
Fixed in f3b174d
