### ISSUE TITLE
Light average chart values don't agree with x axis (?)

### ISSUE THREAD

**Issue by cosmicespresso** [civic-data-design-lab/atlas-lighting#123]
![image](https://cloud.githubusercontent.com/assets/10440556/23493490/28e40158-feda-11e6-82b2-c45b0642b65a.png)

Is the median calculation correct? The brush is around 155 but the value is 74...

**Comment by egeozin** [comment]
I'm not able to replicate that. Can you be specify a little more about how did you reach that, have some other chart changed the average before you interacted with brush? does the problem persists when you make hard refresh?
