### ISSUE TITLE
SELECTED CELL VIEW: Top Insta topics (waiting for data?)

### ISSUE THREAD

**Issue by cosmicespresso** [civic-data-design-lab/atlas-lighting#130]

**Comment by egeozin** [comment]
Yep! You can try with denver and san jose, they are complete.

**Comment by cosmicespresso** [comment]
![image](https://cloud.githubusercontent.com/assets/10440556/23533136/ae2ddd7c-ff7d-11e6-9559-f84c13b286a6.png)

Works! Thanks for the utility function 😄 
The only issue is that it is often empty - should we replace it with a string that says "none recorded" or something?

**Comment by egeozin** [comment]
Sure, will fix it in 10
