### ISSUE TITLE
Misalignment of the charts in the right panel

### ISSUE THREAD

**Issue by egeozin** [civic-data-design-lab/atlas-lighting#135]
<img width="365" alt="slight_misalignment" src="https://cloud.githubusercontent.com/assets/14356218/23570268/76952d8e-0031-11e7-8ee0-a5d3756da2fd.png">

**Comment by cosmicespresso** [comment]
I did this because when we have two decimals and HIGH, it would overlap with the name of the y-axis. I can switch it back!

**Comment by egeozin** [comment]
We can get rid of the decimals, because for other updated on night time intensity average we are already using either Math.round() or toFixed().

**Comment by cosmicespresso** [comment]
Sounds good, will take care of it.

**Comment by egeozin** [comment]
@Kallirroi they still look a bit on the left side, I recall that the left edge of the charts were closer to the right side, I was calculating the quantile lines according to chartMargins, and there is still mismatch on quantile lines.

**Comment by cosmicespresso** [comment]
This looks right to me no?

![image](https://cloud.githubusercontent.com/assets/10440556/23664129/b14aa384-0322-11e7-9eea-9da192287eb1.png)

I had changed the width of this: 
![image](https://cloud.githubusercontent.com/assets/10440556/23664154/c537ec1c-0322-11e7-8c26-146f65f6533d.png)

in order for the `Cell View` to fit properly and avoid vertical scrolling. This resulted in some empty space on the right of the graphs, like so:
![image](https://cloud.githubusercontent.com/assets/10440556/23664222/fb2f0d78-0322-11e7-90d9-49da53b815cc.png)

I never changed the `chartMargins` variable though.

**Comment by egeozin** [comment]
Fixed in a7eeeab.
