### ISSUE TITLE
Cross Filtering

### ISSUE THREAD

**Issue by hgunc** [civic-data-design-lab/atlas-lighting#141]
When you filter lighting intensity, business types or vision api results do not adapt accordingly.

Also Instagram Density Average five >0 value/ Why is that?

<img width="308" alt="screen shot 2017-03-05 at 11 06 54 am" src="https://cloud.githubusercontent.com/assets/24460295/23589008/eedaefc8-0193-11e7-8377-890fcc627050.png">
<img width="308" alt="screen shot 2017-03-05 at 11 06 39 am" src="https://cloud.githubusercontent.com/assets/24460295/23589009/eedf82d6-0193-11e7-935b-441a99927710.png">

**Comment by cosmicespresso** [comment]
Yes the word clouds should be responsive. 
Not sure what you mean by "Also Instagram Density Average five >0 value" ?

**Comment by hgunc** [comment]
The first image, when there a region is selected for lighting intensity, we see there are cells with variant amounts of posts but the average is showing ">0"

Shouldn't it be a value instead?

**Comment by egeozin** [comment]
Average is close to 0 but I can try to get rid of 0 elements on that chart

**Comment by egeozin** [comment]
Ins Density fixed in c75e9c4 . I opened an another issue regarding cross filtering.
