### ISSUE TITLE
Cross Filtering

### ISSUE THREAD

**Issue by egeozin** [civic-data-design-lab/atlas-lighting#146]
When you filter lighting intensity, business types or vision api results do not adapt accordingly.

<img width="308" alt="screen shot 2017-03-05 at 11 06 54 am" src="https://cloud.githubusercontent.com/assets/24460295/23589008/eedaefc8-0193-11e7-8377-890fcc627050.png">
<img width="308" alt="screen shot 2017-03-05 at 11 06 39 am" src="https://cloud.githubusercontent.com/assets/24460295/23589009/eedf82d6-0193-11e7-935b-441a99927710.png">

**Comment by egeozin** [comment]
By the way, we didn't have this functionality before(we should have), the order, number and sizes were changing when a cell is selected.  @hgunc

I'm now implementing this, but I feel like this can be more tricky than it sounds, hope everything turns out ok.

**Comment by egeozin** [comment]
I've implemented this.

@hgunc Can you try this functionality? We have to think about whether to include this functionality, because this might considerably reduce the performance.

Other option is to keep it as before. (This has no harm, we might include a description).

**Comment by cosmicespresso** [comment]
I don't think the performance has suffered (?)
