### ISSUE TITLE
About Page Cosmetics

### ISSUE THREAD

**Issue by hgunc** [civic-data-design-lab/atlas-lighting#157]
ok guys few text edits for about page. This text can be larger font size, maybe full size of the screen.

Today’s digital revolution has radically changed the way we process the volume of information that cities produce every day. Especially with the emergence of digital data and ubiquitous use of mobile social network services, new opportunities arise for researchers to develop tools grounded in new data sources. What makes these sources particularly useful for geospatial analysis is that they are available across municipal, provincial, and national borders. Wherever the web service has users, data is available which means that researchers are no longer dependent on conventional data sources.

Atlas of Lighting is a joint project between Philips, MIT Center for Advanced Urbanism and MIT Civic Data Design Lab that responds to the need for for an integrated and scientific understanding of the dynamics of metropolitan areas around the world. It is an interactive mapping tool in which the user can combine, isolate or cross-reference both quantitative and qualitative datasets to get a clear view of how cities operate.

The Atlas uses interactive visualization techniques to enable users to manipulate the data, changing the mode of display, and adjusting variables of interest. With each query to a dataset, other data sets update themselves automatically, revealing dynamic relationships between variables. Users can also explore the data for one grid cell, including fine-grained data such as all the Instagram posts located in a cell. The customizable interface allows users to choose their data and investigate relationships across multiple scales. 

Atlas of Lighting aims to make comparative analysis of metro areas more accessible in order to guide policymakers to make integrated and science-based decisions.

**Comment by hgunc** [comment]
First title will be "About" instead of Team

![screen shot 2017-03-07 at 10 32 35 pm](https://cloud.githubusercontent.com/assets/24460295/23689177/ef9f32c6-0386-11e7-9292-28cf825fab98.jpg)

**Comment by hgunc** [comment]
Let's replace Data section with this:

Business Density
Source: Google Places API
Year: 2016
Indicates total number of Google Places in a grid cell, which includes businesses, institutions, parks, and other points of interest.

Business Type
Source: Google Places API
Year: 2016
Indicates the types of the local businesses in a grid cell, using Google Places classifications.

Business Type Diversity
Source: Google Places API
Year: 2016
Provides an index value representing the diversity of business types in a grid cell, which increases with business density and variety of business types, using the Google Places classifications.

Opening Hour Index
Source: Google Places API
Year: 2016
Indicates the percentage and the average number of businesses that are open per hour in a given period of time in a grid cell.

Business Price Category
Source: Google Places API
Year: 2016
Indicates the average price level of a grid cell, using Google Places classifications.
0 — Free; 1 — Inexpensive; 2 — Moderate; 3 — Expensive; 4 — Very Expensive.

Instagram Post Density
Source: Instagram API
Year: 2016
Indicates total number of Instagram posts geo-tagged in a grid cell.

Instagram Likes Density
Source: Instagram API
Year: 2016
Indicates total number of all the likes that are attached to Instagram posts geo-tagged in a grid cell.

Instagram Post Thumbnails
Source: Instagram API
Year: 2016
Provides a collection of Instagram media thumbnails in a selected grid cell.

Instagram Content Topics
Source: Google Vision API
Year: 2016
Provides a collection of topics that describe the content of Instagram media, using machine learning tools from the Google Vision API.

Demographics

Population Density
Source: ACS 5 Year Estimate
Year: 2010-2014
Indicates the number people in a given unit area, commonly represented as population per square mile.

Household Median Income
Source: ACS 5 Year Estimates
Year: 2010-2014
Indicates the median value of the combined incomes of people sharing a household or place of residence. Census block group values are redistributed to each grid cell using ArcGIS.

Development Intensity
Source: National Land Cover Database
Year: 2011
Indicates characteristics and classification of the land surface such as urban, agricultural, and forest, as well as percent impervious surface.

Google Street View
Source: Google Street View API
Year: 2016
Provides 360-degree, panoramic, and street-level imagery from the centroid point in a selected grid cell.

**Comment by thuytle** [comment]
<img width="1436" alt="screen shot 2017-03-07 at 11 40 41 pm" src="https://cloud.githubusercontent.com/assets/1759051/23690445/b5c77d52-038f-11e7-8da8-ad5143fe5faf.png">

the Data section ends up becoming really long, is that a problem?

**Comment by hgunc** [comment]
I think we should make the line heights of team members less.

So team section should occupy half of the page, data should compose the other. For data, maybe a bounding box and the user  should be able to scroll inside it.
