### ISSUE TITLE
Dataset Descriptions

### ISSUE THREAD

**Issue by hgunc** [civic-data-design-lab/atlas-lighting#158]
Here is the most updated descriptions for each dataset. Would be great if we have source for all, will need to change the styling

Business Density
Source: Google Places API
Year: 2016
Indicates total number of Google Places in a grid cell, which includes businesses, institutions, parks, and other points of interest.

Business Type
Source: Google Places API
Year: 2016
Indicates the types of the local businesses in a grid cell, using Google Places classifications.

Business Type Diversity
Source: Google Places API
Year: 2016
Provides an index value representing the diversity of business types in a grid cell, which increases with business density and variety of business types, using the Google Places classifications. 

Opening Hour Index
Source: Google Places API
Year: 2016
Indicates the percentage and the average number of businesses that are open per hour in a given period of time in a grid cell. 

Business Price Category
Source: Google Places API
Year: 2016
Indicates the average price level of a grid cell, using Google Places classifications.
0 — Free; 1 — Inexpensive; 2 — Moderate; 3 — Expensive; 4 — Very Expensive.

Instagram Post Density
Source:  Instagram API
Year: 2016
Indicates total number of Instagram posts geo-tagged in a grid cell.

Instagram Likes Density
Source: Instagram API
Year: 2016
Indicates total number of all the likes that are attached to Instagram posts geo-tagged in a grid cell.

Instagram Post Thumbnails
Source: Instagram API
Year: 2016
Provides a collection of Instagram media thumbnails in a selected grid cell.

Instagram Content Topics
Source: Google Vision API
Year: 2016
Provides a collection of topics that describe the content of Instagram media, using machine learning tools from the Google Vision API.

Demographics

Population Density
Source: ACS 5 Year Estimate
Year: 2010-2014
Indicates the number people in a given unit area, commonly represented as population per square mile.

Household Median Income
Source: ACS 5 Year Estimates
Year: 2010-2014
Indicates the median value of the combined incomes of people sharing a household or place of residence. Census block group values are redistributed to each grid cell using ArcGIS.

Development Intensity
Source: National Land Cover Database
Year: 2011
Indicates characteristics and classification of the land surface such as urban, agricultural, and forest, as well as percent impervious surface.

Google Street View
Source: Google Street View API
Year: 2016
Provides 360-degree, panoramic, and street-level imagery from the centroid point in a selected grid cell.

**Comment by hgunc** [comment]
Suggestion:

Source replaces the blue placeholder

![screen shot 2017-03-07 at 10 26 40 pm](https://cloud.githubusercontent.com/assets/24460295/23688952/8b431e1a-0385-11e7-9719-ed239b696d9a.jpg)

**Comment by cosmicespresso** [comment]
@hgunc thats too much text and line breaks for this amount of space. Alternative?

**Comment by hgunc** [comment]
@Kallirroi just the description then.

all the other info can go in to about page

**Comment by cosmicespresso** [comment]
I fit the description and the source, see below: 
![image](https://cloud.githubusercontent.com/assets/10440556/23691178/db3b160c-0394-11e7-9426-0b3eed05d519.png)
