### ISSUE TITLE
Comparison Case Study

### ISSUE THREAD

**Issue by hgunc** [civic-data-design-lab/atlas-lighting#160]
@thuytle 

I need you to create a case study page with the plot chart and the map.

![crosscity](https://cloud.githubusercontent.com/assets/24460295/23710319/4ea9c2dc-03ea-11e7-9b2b-9a27e7b59f16.jpg)

**Comment by hgunc** [comment]
Do you think you can do this by 6 pm today? Please make sure that we are not creating extra bugs, if you think it is complicated just don't do it. No slider or anything. Simple page with the interactive chart.

@egeozin we need to add a dropdown menu to case study. it should be renamed "Case Studies" and add two pages underneath. 1- Cross Metro Comparison 2- Light Use in Different Income Groups

**Comment by cosmicespresso** [comment]
Sorry to jump in, but I think thats too late, as it will certainly generate bugs which we have no time to fix. This should have been addressed earlier - I thought that we had dropped Case Study 2 for good.

**Comment by hgunc** [comment]
This was already built and working, what do you think will create a problem?

**Comment by cosmicespresso** [comment]
Because the 2D bubble chart was not working properly. 
How about this: @thuytle give it a shot and let me know if you need help, I can work on stuff until 8pm today. You might have to check the `script` tags to make sure that they are included, since maybe they are now removed from the `grid.html` file.

**Comment by hgunc** [comment]
Ok @thuytle  give it a shot and communicate with Kalli and Ege please

**Comment by sw2279** [comment]
Unless it's a slide show it's going to create tons of bugs. The only option for inclusion is to add a case studies than insert two slide shows. Not sure if we can do that.

**Comment by thuytle** [comment]
@Kallirroi Kalli, what on the bubble chart wasn't working for you? I'm working on the one on index.html -- seems to work fine

**Comment by hgunc** [comment]
@sw2279 says it is going to create bugs. So if you could work on it independent from the online version please do it. But please don't change anything with what we have on the website now.

**Comment by cosmicespresso** [comment]
Try it out as a standalone page and when you are sure the console is clean of any errors then connect it to the rest 

Kalli

Envoyé de mon iPhone

**Comment by thuytle** [comment]
it's working in index.html as shown. I haven't put links to it anywhere yet

<img width="1440" alt="screen shot 2017-03-08 at 4 37 19 pm" src="https://cloud.githubusercontent.com/assets/1759051/23725225/b94c9e74-041d-11e7-86b5-d3ca9893f630.png">

**Comment by cosmicespresso** [comment]
does the 2D chart also work? If yes, I can take it from here.

**Comment by cosmicespresso** [comment]
Also, @thuytle: 

1. the page you are building should be in a file other than index.html. Don't touch the index.html that already existed, rather do what you did for the slideshow implementation (make a new .html file).

2. the 2D axis should have dropdowns where the user can select different variables for both x and y axis (this was the idea @hgunc right?). I think this is the part that was not working properly before. 

thank you!!

**Comment by thuytle** [comment]
@Kallirroi 
1. Hey sorry didn't know that's what you guys wanted since when I looked at the index.html today it wasn't working properly. I fixed up the tags and I commented out stuff that we don't need and changed the css but didn't delete anything.

2. I commented out the dropdowns as I thought that's what Hayro meant by "No slider or anything."

**Comment by thuytle** [comment]
@hgunc could you send me the use cases of this case study that we do want to show and how we want to show them? I'm a bit confused so I'll wait for that before I resume working on this so I don't create any problems
