### ISSUE TITLE
Four widgets are already selected on Chicago load

### ISSUE THREAD

**Issue by egeozin** [civic-data-design-lab/atlas-lighting#19]
Business Price, Open Business Index, Instagram Density and Instagram Likes widgets seem to be selected when the Chicago MSA is selected. Only the titles and digits are visible, error is probably bound to html load.

<img width="911" alt="screen shot 2017-02-01 at 8 04 51 pm" src="https://cloud.githubusercontent.com/assets/14356218/22533352/9b69b31a-e8bb-11e6-9fe8-b5302721e4e2.png">

**Comment by hgunc** [comment]
We just want to see the lighting index so we should get rid of them. Just like LA
