### ISSUE TITLE
Some CSS fixes

### ISSUE THREAD

**Issue by cosmicespresso** [civic-data-design-lab/atlas-lighting#37]
![image](https://cloud.githubusercontent.com/assets/10440556/22743748/29ff96e4-ede9-11e6-9d93-a7ad4cd14b55.png)

1. Margin-left of charts a big bigger?
2. $100 instead of 100$

![image](https://cloud.githubusercontent.com/assets/10440556/22743796/5224214e-ede9-11e6-9c66-a132742f96bc.png)

3. break the units line in two?

**Comment by egeozin** [comment]
Fixed
