### ISSUE TITLE
Instagram Likes needs to be shown in range bins

### ISSUE THREAD

**Issue by egeozin** [civic-data-design-lab/atlas-lighting#44]
<img width="380" alt="instagram_likes" src="https://cloud.githubusercontent.com/assets/14356218/22798556/8893dcaa-eed0-11e6-802a-878f511a6556.png">

**Comment by cosmicespresso** [comment]
All of them seem to be zero (?) 🤔 
 
![image](https://cloud.githubusercontent.com/assets/10440556/22813534/65eec90e-ef1a-11e6-9181-d84799802c15.png)

**Comment by egeozin** [comment]
There should be some others but compared to zeros, they are small.

**Comment by cosmicespresso** [comment]
wait - where are we loading this data from? I can't see it in the _grid.csv file.
line 755: `d.insta_like = +d.insta_like ? +d.insta_like : 0;`  just sets them all to zero.

**Comment by egeozin** [comment]
It's before insta_0

**Comment by egeozin** [comment]
When I checked the insta_like array, close to the end there are some non-zero values

**Comment by cosmicespresso** [comment]
well I just realized that LA and San Jose do not have the instagram info ☺️ I was looking at LA.

**Comment by egeozin** [comment]
Oh! So we can "display:none" it on those cities :D

**Comment by egeozin** [comment]
I was looking at Chicago, sorry :).

**Comment by cosmicespresso** [comment]
Ok so the range bins are there but I have trouble with selecting the bar at x=0 - see below:
![image](https://cloud.githubusercontent.com/assets/10440556/22814656/4f407c62-ef23-11e6-9179-5fd49adba0d6.png)
Very bizarre. I have disabled the bar selectivity at the moment.

**Comment by egeozin** [comment]
Hmm interesting! Can you pull/push your changes?

**Comment by cosmicespresso** [comment]
yep just did.

**Comment by egeozin** [comment]
How about completely ignoring 0's in x-axis, so we start from 100 ?

**Comment by egeozin** [comment]
Or how about calling this on the NOT renderlet but passing it as a function in group of instaLikes chart: 

`var filteredFunctionAmountGroup = {
    all: function () {
        return functionAmountGroup.top(Infinity).filter( function (d) { return d.value !== 0; } );
    }
}`

UPDATE This one doesn't work!

**Comment by egeozin** [comment]
I haven't tried it.

**Comment by cosmicespresso** [comment]
![image](https://cloud.githubusercontent.com/assets/10440556/22815594/6696fbdc-ef2a-11e6-87cc-2afeeb4749e3.png)
the problem is that all these bars are separate and not aggregated into one bin..

**Comment by cosmicespresso** [comment]
Check it out now (2239a17) - might need to adjust the y axis

**Comment by egeozin** [comment]
Wonderful! Have you tried omitting the 0 in the x-axis?

**Comment by egeozin** [comment]
Hey Kalli, when grouping InsLikes returning values >= 100 and removing the 0 from ordinal scale x works!

<img width="375" alt="screen shot 2017-02-11 at 2 03 05 pm" src="https://cloud.githubusercontent.com/assets/14356218/22856631/f3dfc2a6-f062-11e6-8909-f7b9973bb265.png">
