### ISSUE TITLE
Scroll is prevented in some cases

### ISSUE THREAD

**Issue by egeozin** [civic-data-design-lab/atlas-lighting#51]
When on a dc chart a brush is present and if the pointer is on that chart it's not possible to scroll between datasets.

**Comment by cosmicespresso** [comment]
https://github.com/dc-js/dc.js/issues/427 maybe helpful? will look into it more later

**Comment by egeozin** [comment]
Saw this, I will look into this later.

**Comment by egeozin** [comment]
Fixed with jeffsteinmetz suggestion:

`
var _nullZoom = function () { return null; }
`
