### ISSUE TITLE
Does the "LOW/MEDIUM/HIGH" change on the light index chart? 

### ISSUE THREAD

**Issue by cosmicespresso** [civic-data-design-lab/atlas-lighting#53]
![image](https://cloud.githubusercontent.com/assets/10440556/22810802/d6d3f3a4-ef08-11e6-8349-925a93d12113.png)

It is always on "LOW" for me :/

**Comment by egeozin** [comment]
It will! In a bit.

**Comment by egeozin** [comment]
My quick fix is to disable the OBI filter from interacting with the light_digits. Let's look at this later @Kallirroi
