### ISSUE TITLE
Intimate zoom in/zoom out buttons when the datasets bar is collapsed

### ISSUE THREAD

**Issue by egeozin** [civic-data-design-lab/atlas-lighting#54]
<img width="147" alt="screen shot 2017-02-10 at 12 07 36 am copy" src="https://cloud.githubusercontent.com/assets/14356218/22814885/39b3b33a-ef25-11e6-9906-60e201c9662a.png">

**Comment by cosmicespresso** [comment]
haha fixed 07d369b
