### ISSUE TITLE
What's up with the about.html ?

### ISSUE THREAD

**Issue by egeozin** [civic-data-design-lab/atlas-lighting#57]
<img width="921" alt="screen shot 2017-02-10 at 1 38 52 am" src="https://cloud.githubusercontent.com/assets/14356218/22816762/d69c8404-ef31-11e6-9ff2-f07feef1d1c9.png">

**Comment by cosmicespresso** [comment]
![image](https://cloud.githubusercontent.com/assets/10440556/22829524/0b7be586-ef71-11e6-8559-c1e3257f40ab.png)
can't reproduce 🤔 

your screenshot looks like the CSS was not fully loaded or something

**Comment by egeozin** [comment]
Can you check the atlas.lighting as well, just to make sure, probably related to cache

**Comment by cosmicespresso** [comment]
Yeah its broken there. I corrected the path to the CSS file in the About page, lets see (6823ecd)

Here is the grid.html:
`  <link rel="stylesheet" type="text/css" href="../stylesheets/atlas.css"> </style>`
and here is the current about.html
`	<link rel="stylesheet" type="text/css" href="stylesheets/atlas.css"> </style>    `
(before that it was `href="atlas.css">`)

**Comment by egeozin** [comment]
Ok the problem is I need to run the initial docker command from the repository in the computing engine. Let's see after then.

**Comment by egeozin** [comment]
Fixed with updating the docker volume in computing engine repo!
