### ISSUE TITLE
On OBI time filter, after exactly 10 changes on the brush I got this error: 

### ISSUE THREAD

**Issue by egeozin** [civic-data-design-lab/atlas-lighting#59]
<img width="757" alt="screen shot 2017-02-10 at 11 46 29 am" src="https://cloud.githubusercontent.com/assets/14356218/22835477/e1aa9296-ef86-11e6-9d4f-f74636102005.png">

**Comment by cosmicespresso** [comment]
hey - after I merged your latest commits the filter does not work at all (it does not influence the map, the light average and the bottom graph does not show anything). Working on it, but might be sth you did in your last two commits?


Update: after resetting to my last commit https://github.com/civic-data-design-lab/atlas-lighting/commit/6823ecd5ce123853e5923c98b8fadc872812b960 the graphs work fine, the map and light index are fully responsive, but I still get the error after more than 10 changes. 

Will keep working on it - meanwhile I won't integrate your last commits.

**Comment by egeozin** [comment]
It works fine in my local! Don't know what happened, let me check.

**Comment by egeozin** [comment]
Are you sure? Can you try again, it works fine in mine, until 10 changes on OBI filters.
I will look into your commits.

**Comment by egeozin** [comment]
I checked my last four commit and I couldn't find anything that can influence your updates and filter.
Only thing that may look different is that I truncated the decimal values from light chart(upon interaction with OBI filter, sometimes that may seem not to be updating, but because sometimes it updates in decimals, we are not seeing that change) .

**Comment by cosmicespresso** [comment]
d4f12e5 think solved it? Check on your side!

**Comment by egeozin** [comment]
Looks like it's fixed! Well done Kalli!
