### ISSUE TITLE
(from Thuy's email)  - income chart

### ISSUE THREAD

**Issue by cosmicespresso** [civic-data-design-lab/atlas-lighting#60]
> I’m having trouble getting the map to sync with the income chart after I change the range.

**Comment by egeozin** [comment]
Kalli, I just checked that in atlas.lighting income chart syncs well with map in both ways. Have you checked in your localhost to see if it works? It works in mine.

**Comment by thuytle** [comment]
hi sorry I meant on the case studies (case 2 - page 2-5) page where I changed the focus range of the chart I couldn't get the map to sync yet so was wondering if either of you have any idea

**Comment by egeozin** [comment]
I will look into this later today. Will keep you updated.

**Comment by egeozin** [comment]
Solved this by changing dc.redrawAll() to incomeChart._doRedraw(). I will look into the street_view part later. It should not be a priority.

**Comment by thuytle** [comment]
it still doesn't work even with the incomeChart._doRedraw()

I tried different things but haven't figured it out, let me know if anyone has more insight into this

**Comment by egeozin** [comment]
Ok I'm looking into this. The promising part about this is that as soon as you start manipulating the brush it shows the quantiles and median values correctly. The likely cause of error is that the doRedraw function is not working properly, I will try to replace it with something else.

**Comment by cosmicespresso** [comment]
From the current discussion with Hayro and Sarah: The case studies will be simplified to a slideshow. Closing this issue.
