### ISSUE TITLE
CASE STUDIES 1: dropdown x and y axis on bubble chart not visible

### ISSUE THREAD

**Issue by cosmicespresso** [civic-data-design-lab/atlas-lighting#63]
![image](https://cloud.githubusercontent.com/assets/10440556/22856879/a11783b4-f068-11e6-9d52-aa389f672c30.png)

**Comment by cosmicespresso** [comment]
Not harmless 
![image](https://cloud.githubusercontent.com/assets/10440556/22866150/51c269b4-f13f-11e6-84a1-49c245381d61.png)

the buttons dont work

**Comment by cosmicespresso** [comment]
I think the issue is in the `function drawChart(data,xLabel,yLabel,rLabel){` function of the `front_page_map_2.js` file

**Comment by egeozin** [comment]
Do you have time to look at this?

**Comment by cosmicespresso** [comment]
yes I can look into this in a bit - both axis are also missing, correct?

**Comment by cosmicespresso** [comment]
e6d40d3 fixes errors but dropdown axis are still not there - they should be visible, right?

**Comment by egeozin** [comment]
What was the dropdown axis? I can see the y and x?

**Comment by cosmicespresso** [comment]
There were two dropdowns, one for x axis and one for y axis - you could select a value for each. My guess is that this variable: `var list= ["Land_Area","MAX","Average_Sum_of_Light","Sum_of_Light","Population_in_2000","Population_2014","Population_Change","Density_2000","Density_2014","Land_Area","GMP_2013","Sum_of_Light_Per_Capita"]` defines the available selections. 

(taken from `front_page_map_2.js`)

@thuytle maybe you can help us out here? :) Not sure if what I'm saying is correct!

**Comment by egeozin** [comment]
Oh got it! Yep, I don't see them.

**Comment by cosmicespresso** [comment]
The problem is the `<select>` tag - when I change it to a `div` it works (of course it needs to be fixed to look like a dropdown).

Did anyone add/remove/change the script tags in the `grid.html`? Its not a browser issue (tested on Safari).

![image](https://cloud.githubusercontent.com/assets/10440556/22993922/d14a5f66-f392-11e6-9b46-08552013c260.png)

**Comment by cosmicespresso** [comment]
update: the CSS sourcing was wrong. Fixed with  c574de4. 
The dropdown menus show but the CSS looks wrong - @thuytle maybe you can look into this?

**Comment by cosmicespresso** [comment]
693fca8 fixes the CSS issues.
