### ISSUE TITLE
CASE STUDIES 1+2: error after clicking on "Close Case Studies" button

### ISSUE THREAD

**Issue by cosmicespresso** [civic-data-design-lab/atlas-lighting#66]
![image](https://cloud.githubusercontent.com/assets/10440556/22870149/f28d0c72-f172-11e6-8240-a5455e2d7869.png)

**Comment by cosmicespresso** [comment]
`grid` is undefined in the `function dataDidLoad(error, grid, chicago_data)` call

**Comment by egeozin** [comment]
Can you pull latest changes, this has not been solved but I have few updates.

**Comment by egeozin** [comment]
Case studies part demands at least a day to solve bugs that are both posted here, and the ones that I recently found out.

**Comment by egeozin** [comment]
Close Case Studies button or the Back to Map button I recently added instead of Next at the last case should return the original datasets configuration.

**Comment by thuytle** [comment]
the close case studies should have been replaced with case study title & the switch to map function is now with the dataset tab (per Hayro's prescriptions)
