### ISSUE TITLE
CASE STUDY 1: Missing text in steps 2, 3, 4

### ISSUE THREAD

**Issue by egeozin** [civic-data-design-lab/atlas-lighting#67]

**Comment by hgunc** [comment]
We don't have the text for this yet. Lets pull it down

**Comment by cosmicespresso** [comment]
whats the status on this issue guys?

**Comment by thuytle** [comment]
Still waiting for text from Hayro I think, in the meantime case 1 is hidden

**Comment by cosmicespresso** [comment]
From the current discussion with Hayro and Sarah: The case studies will be simplified to a slideshow. Closing this issue.
