### ISSUE TITLE
CASE STUDY 2: After the initial load > after clicking on case studies > Have to click on Case Studies 2 two times.

### ISSUE THREAD

**Issue by egeozin** [civic-data-design-lab/atlas-lighting#68]
In order to go through the Case Study 2: Chicago

**Comment by egeozin** [comment]
Please pull the latest changes before commit.

**Comment by cosmicespresso** [comment]
I just had to click 5 times - it must be some event handler that is busy with something else. Clicking on the "close" button (3 times) led to this:
![image](https://cloud.githubusercontent.com/assets/10440556/22893423/a74ce40a-f1e3-11e6-896d-5954f3fb59a8.png)


@egeozin - maybe we should consider not showing this entire tab for the moment?? as you said, it needs at least a day to debug... :/

**Comment by egeozin** [comment]
Seems to me a good idea!

**Comment by hgunc** [comment]
Hey guys,
Yes lets pull down case studies tab for now. But this should be top of our urgency list.

**Comment by thuytle** [comment]
it's fixed

**Comment by thuytle** [comment]
it's fixed
