### ISSUE TITLE
What was the reason for initial filtering? Is that because of the OBI chart?

### ISSUE THREAD

**Issue by egeozin** [civic-data-design-lab/atlas-lighting#70]
So the one on the left is the initial map, the one on the right is all cells made visible after business types chart clicking and re-clicking on a type. I'm close to making a mutually filterable non-dc and dc charts mechanism but I only wonder the reason for initial filtering.

![cell_state_change](https://cloud.githubusercontent.com/assets/14356218/22913629/fe7899bc-f239-11e6-8040-ac7efcebea1f.jpg)

**Comment by egeozin** [comment]
Ignore this. It's because I have changed the timeselector brush to be set between 6 -18

**Comment by egeozin** [comment]
Nope it's not that.

**Comment by cosmicespresso** [comment]
Not sure I understand the question - the filtering (in the word cloud) was always a desired functionality, from what I remember. Explain more? :)

**Comment by egeozin** [comment]
Before it comes to filtering with word cloud, our map is already filtered. Two days ago I changed the filterhour filtering 6 - 18 instead of 0 - 24 but that is not the sole reason for this filtering.

--> The thing is we are already filtering our data somewhere but because in my old word cloud filtering function I make every cell visible, only then I'm able to see like the one on the right.

So I would like to know where does our initial filtering comes from that makes a user who is interacting with the map first time, sees the one on the left.

**Comment by cosmicespresso** [comment]
Got it. I had the same thoughts when I was building the time filter. I will double check that its not filtering, but another thought (from quickly looking at `filterhour` callbacks) is the call from within the `incomeChart.on('renderlet', function (chart) {.....}` function (line 914).

Why does the income chart renderlet need to call the time filter? 🤔

**Comment by egeozin** [comment]
Nice question, would you be available tomorrow to meet in person? I have some ideas about integrating  a more central filtering mechanism for OBI and word cloud charts so they don't influence each other. I made a prototype, but it has one strange behavior that I think I have to solve.

**Comment by egeozin** [comment]
A hangout would suffice as well.
