### ISSUE TITLE
Street view not working properly

### ISSUE THREAD

**Issue by thuytle** [civic-data-design-lab/atlas-lighting#71]
Street view doesn't show up properly after being dragged into the drop zone

**Comment by cosmicespresso** [comment]
The element exists in the DOM, but doesn't show.

![image](https://cloud.githubusercontent.com/assets/10440556/22953310/996575c2-f2de-11e6-988b-f27df08bca83.png)

(after looking into this a bit) - its a confusion between `opacity` and `display` controlling whether it shows up or not - this previous issue is relevant: https://github.com/civic-data-design-lab/atlas-lighting/issues/41

**Comment by cosmicespresso** [comment]
d4353fe  fixes it (? can you both check?)

**Comment by cosmicespresso** [comment]
![image](https://cloud.githubusercontent.com/assets/10440556/22954657/bfd46af4-f2e5-11e6-9df9-d30860e6606a.png)

wtf this is absurd - I assume streetview is not supposed to creep up down there right?

**Comment by hgunc** [comment]
Refer to this document: https://www.dropbox.com/s/obuuvm3oayy5k4x/161207_casestudy.pdf?dl=0

Streetview should be on the page if that's what you are asking. Basically we want to highlight a single cell with high lighting and low income and show it is dense urban neighborhood whereas the next page showing a cell with low lighting high income suburban settlement

**Comment by cosmicespresso** [comment]
Can't access the link above - but its OK if this is indeed how the study case should look like (?). If so, we can close this issue.
