### ISSUE TITLE
Cities other than Chicago malfuntions?

### ISSUE THREAD

**Issue by thuytle** [civic-data-design-lab/atlas-lighting#79]
<img width="1193" alt="screen shot 2017-02-17 at 2 53 55 pm" src="https://cloud.githubusercontent.com/assets/1759051/23081015/0977b2d2-f521-11e6-9040-115961f42881.png">

**Comment by egeozin** [comment]
I now see that we have two JSON objects named cityCentroids, one in city_comparisons_data.js and other in front_page_map_2.js. I just assigned a different name to the one on front_page_map_2.js.
