### ISSUE TITLE
Insta likes for LA

### ISSUE THREAD

**Issue by cosmicespresso** [civic-data-design-lab/atlas-lighting#87]

**Comment by egeozin** [comment]
We don't have the insta_like data field for LA_grid.csv file, that's why.

**Comment by cosmicespresso** [comment]
Is Dennis taking care of this?

**Comment by egeozin** [comment]
I just sent an email

**Comment by cosmicespresso** [comment]
It works with the other .csv file. I emailed Dennis about it. The OBI percent does not work with that .csv file though. I think the two need to be merged.

![image](https://cloud.githubusercontent.com/assets/10440556/23525549/d98f50fc-ff5c-11e6-8dba-49ac87ac9f92.png)

**Comment by egeozin** [comment]
Fixed with dataset update in 2987503
