### ISSUE TITLE
Business price 'undefined' if choose range higher than 3 

### ISSUE THREAD

**Issue by thuytle** [civic-data-design-lab/atlas-lighting#91]
<img width="1430" alt="screen shot 2017-02-23 at 6 15 24 pm" src="https://cloud.githubusercontent.com/assets/1759051/23283484/234cc8fa-f9f4-11e6-9a50-812160755cbe.png">

**Comment by cosmicespresso** [comment]
![image](https://cloud.githubusercontent.com/assets/10440556/23517608/db98991c-ff3e-11e6-97ee-a44ae9a03d70.png)

Can't replicate - close if bug is not there.
