### ISSUE TITLE
All cells flash on tag release when brushed

### ISSUE THREAD

**Issue by egeozin** [civic-data-design-lab/atlas-lighting#95]

**Comment by cosmicespresso** [comment]
Not sure if this is still an issue?

**Comment by egeozin** [comment]
Yep! But I'm on this. This will be solved.

So this happens when you have a brush and a tag selected either in busTypes/InstaTopics and when you release the tag.

I will alter the filterCells function, so when a brush is present there will be no cell display loops in between.

**Comment by egeozin** [comment]
Fixed in c7a9e87
